/* The following code was generated by JFlex 1.4.3 on 16/11/19 06:38 PM */

package codigo;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 16/11/19 06:38 PM from the specification file
 * <tt>C:/Users/gugj9/OneDrive/Documentos/ITSUR/Metodos_Numericos/AnalizadorLexico/src/codigo/LexerCup.flex</tt>
 */
class LexerCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  8,  0,  0,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  0,  0,  0,  0, 38,  0, 35, 36, 37, 38, 38,  1, 13,  9,  7, 
     3,  3,  3,  3,  3,  3,  3,  3,  3,  3, 16, 15, 10, 12, 11,  0, 
     0,  5, 30, 20, 32, 28, 17, 25, 31, 21,  2,  2, 24, 27, 19, 23, 
     4, 33,  6, 29, 26, 18, 34,  2,  2, 14,  2,  0,  0,  0,  0,  2, 
     0,  5, 30, 20, 32, 28, 17, 25, 31, 21,  2,  2, 24, 27, 19, 22, 
     4, 33,  6, 29, 26, 18, 34,  2,  2,  2,  2,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\3\3\2\5\3\6"+
    "\1\7\1\10\1\11\13\3\1\1\1\12\1\13\1\0"+
    "\3\3\1\14\1\15\3\3\1\16\5\3\1\17\5\3"+
    "\1\0\1\20\1\0\1\21\20\3\1\22\1\3\1\0"+
    "\1\23\12\3\1\24\3\3\1\25\5\3\1\4\2\3"+
    "\1\26\5\3\1\27\5\3\1\30\1\31\23\3\1\32"+
    "\1\33\1\34\4\3\1\35\12\3\1\36\1\37\1\40"+
    "\1\41\1\42\1\3\1\43\5\3\1\44\1\3\1\45"+
    "\1\3\1\46\1\47";

  private static int [] zzUnpackAction() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\165\0\234\0\303\0\352\0\u0111"+
    "\0\u0138\0\47\0\u015f\0\u0186\0\47\0\165\0\47\0\47"+
    "\0\u01ad\0\u01d4\0\u01fb\0\u0222\0\u0249\0\u0270\0\u0297\0\u02be"+
    "\0\u02e5\0\u030c\0\u0333\0\u035a\0\u0381\0\47\0\u03a8\0\u03cf"+
    "\0\u03f6\0\u041d\0\u0444\0\47\0\u046b\0\u0492\0\u04b9\0\165"+
    "\0\u04e0\0\u0507\0\u052e\0\u0555\0\u057c\0\u05a3\0\u05ca\0\u05f1"+
    "\0\u0618\0\u063f\0\u0666\0\u035a\0\u035a\0\u068d\0\u03a8\0\u06b4"+
    "\0\u06db\0\u0702\0\u0729\0\u0750\0\u0777\0\u079e\0\u07c5\0\u07ec"+
    "\0\u0813\0\u083a\0\u0861\0\u0888\0\u08af\0\u08d6\0\u08fd\0\165"+
    "\0\u0924\0\u094b\0\165\0\u0972\0\u0999\0\u09c0\0\u09e7\0\u0a0e"+
    "\0\u0a35\0\u0a5c\0\u0a83\0\u0aaa\0\u0ad1\0\165\0\u0af8\0\u0b1f"+
    "\0\u0b46\0\165\0\u0b6d\0\u0b94\0\u0bbb\0\u0be2\0\u0c09\0\47"+
    "\0\u0c30\0\u0c57\0\165\0\u0c7e\0\u0ca5\0\u0ccc\0\u0cf3\0\u0d1a"+
    "\0\165\0\u0d41\0\u0d68\0\u0d8f\0\u0db6\0\u0ddd\0\165\0\165"+
    "\0\u0e04\0\u0e2b\0\u0e52\0\u0e79\0\u0ea0\0\u0ec7\0\u0eee\0\u0f15"+
    "\0\u0f3c\0\u0f63\0\u0f8a\0\u0fb1\0\u0fd8\0\u0fff\0\u1026\0\u104d"+
    "\0\u1074\0\u109b\0\u10c2\0\165\0\165\0\165\0\u10e9\0\u1110"+
    "\0\u1137\0\u115e\0\165\0\u1185\0\u11ac\0\u11d3\0\u11fa\0\u1221"+
    "\0\u1248\0\u126f\0\u1296\0\u12bd\0\u12e4\0\165\0\165\0\165"+
    "\0\165\0\165\0\u130b\0\165\0\u1332\0\u1359\0\u1380\0\u13a7"+
    "\0\u13ce\0\165\0\u13f5\0\165\0\u141c\0\165\0\165";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\3\1\12\1\13\1\14\1\15\1\12\1\16\1\17"+
    "\1\20\1\21\1\4\1\22\1\23\2\4\1\16\1\24"+
    "\2\4\1\25\1\26\1\27\1\4\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\12\50\0\1\3\6\0"+
    "\1\3\40\0\5\4\7\0\1\4\2\0\22\4\7\0"+
    "\1\5\5\0\1\37\37\0\3\4\1\40\1\4\7\0"+
    "\1\4\2\0\22\4\6\0\5\4\7\0\1\4\2\0"+
    "\7\4\1\41\12\4\6\0\5\4\7\0\1\4\2\0"+
    "\13\4\1\42\6\4\13\0\1\43\53\0\1\15\1\44"+
    "\45\0\1\15\34\0\3\4\1\45\1\4\7\0\1\4"+
    "\2\0\1\4\1\46\2\4\1\47\15\4\6\0\5\4"+
    "\7\0\1\4\2\0\5\4\2\50\13\4\6\0\5\4"+
    "\7\0\1\4\2\0\5\4\2\51\13\4\6\0\5\4"+
    "\7\0\1\4\2\0\13\4\1\52\6\4\6\0\5\4"+
    "\7\0\1\4\2\0\4\4\1\53\15\4\6\0\5\4"+
    "\7\0\1\4\2\0\2\4\1\54\11\4\1\55\5\4"+
    "\6\0\5\4\7\0\1\4\2\0\4\4\1\56\6\4"+
    "\1\57\6\4\6\0\3\4\1\60\1\4\7\0\1\4"+
    "\2\0\22\4\6\0\5\4\7\0\1\4\2\0\13\4"+
    "\1\61\6\4\6\0\5\4\7\0\1\4\2\0\1\4"+
    "\1\62\20\4\6\0\5\4\7\0\1\4\2\0\13\4"+
    "\1\63\6\4\4\0\10\64\1\0\32\64\1\65\3\64"+
    "\15\0\1\66\34\0\1\67\45\0\4\4\1\70\7\0"+
    "\1\4\2\0\22\4\6\0\5\4\7\0\1\4\2\0"+
    "\10\4\1\71\11\4\6\0\2\4\1\72\2\4\7\0"+
    "\1\4\2\0\22\4\4\0\10\43\1\0\36\43\2\0"+
    "\5\4\7\0\1\4\2\0\7\4\1\73\12\4\6\0"+
    "\5\4\7\0\1\4\2\0\2\4\1\74\17\4\6\0"+
    "\5\4\7\0\1\4\2\0\2\4\1\75\17\4\6\0"+
    "\5\4\7\0\1\4\2\0\2\4\1\76\17\4\6\0"+
    "\5\4\7\0\1\4\2\0\13\4\1\77\6\4\6\0"+
    "\5\4\7\0\1\4\2\0\13\4\1\100\6\4\6\0"+
    "\5\4\7\0\1\4\2\0\11\4\1\101\10\4\6\0"+
    "\5\4\7\0\1\4\2\0\3\4\1\102\16\4\6\0"+
    "\5\4\7\0\1\4\2\0\2\4\1\103\17\4\6\0"+
    "\5\4\7\0\1\4\2\0\10\4\1\104\11\4\6\0"+
    "\5\4\7\0\1\4\2\0\3\4\1\105\10\4\1\106"+
    "\5\4\6\0\5\4\7\0\1\4\2\0\5\4\2\107"+
    "\13\4\6\0\5\4\7\0\1\4\2\0\13\4\1\110"+
    "\6\4\6\0\4\4\1\111\7\0\1\4\2\0\22\4"+
    "\7\0\1\112\45\0\3\4\1\113\1\4\7\0\1\4"+
    "\2\0\22\4\6\0\5\4\7\0\1\4\2\0\5\4"+
    "\2\114\13\4\6\0\5\4\7\0\1\4\2\0\13\4"+
    "\1\115\6\4\6\0\5\4\7\0\1\4\2\0\14\4"+
    "\1\116\5\4\6\0\5\4\7\0\1\4\2\0\3\4"+
    "\1\117\16\4\6\0\2\4\1\120\1\121\1\4\7\0"+
    "\1\4\2\0\1\122\11\4\1\123\1\4\1\124\5\4"+
    "\6\0\2\4\1\125\2\4\7\0\1\4\2\0\22\4"+
    "\6\0\4\4\1\126\7\0\1\4\2\0\22\4\6\0"+
    "\5\4\7\0\1\4\2\0\2\4\1\127\17\4\6\0"+
    "\5\4\7\0\1\4\2\0\5\4\2\130\13\4\6\0"+
    "\4\4\1\131\7\0\1\4\2\0\22\4\6\0\5\4"+
    "\7\0\1\4\2\0\5\4\2\132\13\4\6\0\5\4"+
    "\7\0\1\4\2\0\1\4\1\133\20\4\6\0\5\4"+
    "\7\0\1\4\2\0\13\4\1\134\6\4\6\0\5\4"+
    "\7\0\1\4\2\0\11\4\1\135\10\4\6\0\5\4"+
    "\7\0\1\4\2\0\11\4\1\136\10\4\6\0\5\4"+
    "\7\0\1\4\2\0\17\4\1\137\2\4\7\0\1\112"+
    "\41\0\1\140\3\0\4\4\1\141\7\0\1\4\2\0"+
    "\22\4\6\0\5\4\7\0\1\4\2\0\11\4\1\142"+
    "\10\4\6\0\5\4\7\0\1\4\2\0\5\4\2\143"+
    "\13\4\6\0\5\4\7\0\1\4\2\0\4\4\1\144"+
    "\15\4\6\0\3\4\1\145\1\4\7\0\1\4\2\0"+
    "\22\4\6\0\5\4\7\0\1\4\2\0\7\4\1\146"+
    "\12\4\6\0\5\4\7\0\1\4\2\0\1\4\1\147"+
    "\20\4\6\0\5\4\7\0\1\4\2\0\4\4\1\150"+
    "\15\4\6\0\5\4\7\0\1\4\2\0\4\4\1\151"+
    "\6\4\1\152\6\4\6\0\3\4\1\153\1\4\7\0"+
    "\1\4\2\0\22\4\6\0\5\4\7\0\1\4\2\0"+
    "\11\4\1\154\10\4\6\0\5\4\7\0\1\4\2\0"+
    "\2\4\1\155\17\4\6\0\5\4\7\0\1\4\2\0"+
    "\4\4\1\156\15\4\6\0\5\4\7\0\1\4\2\0"+
    "\2\4\1\157\17\4\6\0\4\4\1\160\7\0\1\4"+
    "\2\0\22\4\6\0\3\4\1\161\1\4\7\0\1\4"+
    "\2\0\22\4\6\0\4\4\1\162\7\0\1\4\2\0"+
    "\22\4\6\0\3\4\1\163\1\4\7\0\1\4\2\0"+
    "\22\4\6\0\5\4\7\0\1\4\2\0\4\4\1\164"+
    "\15\4\6\0\5\4\7\0\1\4\2\0\4\4\1\165"+
    "\15\4\6\0\5\4\7\0\1\4\2\0\5\4\2\166"+
    "\13\4\6\0\4\4\1\167\7\0\1\4\2\0\22\4"+
    "\6\0\5\4\7\0\1\4\2\0\10\4\1\170\11\4"+
    "\6\0\5\4\7\0\1\4\2\0\2\4\1\171\17\4"+
    "\6\0\5\4\7\0\1\4\2\0\13\4\1\172\6\4"+
    "\6\0\5\4\7\0\1\4\2\0\10\4\1\173\11\4"+
    "\6\0\5\4\7\0\1\4\2\0\14\4\1\174\5\4"+
    "\6\0\4\4\1\175\7\0\1\4\2\0\22\4\6\0"+
    "\5\4\7\0\1\4\2\0\3\4\1\176\16\4\6\0"+
    "\5\4\7\0\1\4\2\0\15\4\1\177\4\4\6\0"+
    "\5\4\7\0\1\4\2\0\20\4\1\200\1\4\6\0"+
    "\5\4\7\0\1\4\2\0\5\4\2\201\13\4\6\0"+
    "\5\4\7\0\1\4\2\0\17\4\1\202\2\4\6\0"+
    "\5\4\7\0\1\4\2\0\11\4\1\203\10\4\6\0"+
    "\4\4\1\204\7\0\1\4\2\0\22\4\6\0\5\4"+
    "\7\0\1\4\2\0\2\4\1\205\17\4\6\0\3\4"+
    "\1\206\1\4\7\0\1\4\2\0\22\4\6\0\5\4"+
    "\7\0\1\4\2\0\5\4\2\207\13\4\6\0\5\4"+
    "\7\0\1\4\2\0\3\4\1\210\16\4\6\0\5\4"+
    "\7\0\1\4\2\0\2\4\1\211\17\4\6\0\5\4"+
    "\7\0\1\4\2\0\1\4\1\212\20\4\6\0\5\4"+
    "\7\0\1\4\2\0\5\4\2\213\13\4\6\0\3\4"+
    "\1\214\1\4\7\0\1\4\2\0\22\4\6\0\5\4"+
    "\7\0\1\4\2\0\13\4\1\215\6\4\6\0\5\4"+
    "\7\0\1\4\2\0\4\4\1\216\15\4\6\0\5\4"+
    "\7\0\1\4\2\0\1\4\1\217\20\4\6\0\5\4"+
    "\7\0\1\4\2\0\12\4\1\220\7\4\6\0\5\4"+
    "\7\0\1\4\2\0\13\4\1\221\6\4\6\0\5\4"+
    "\7\0\1\4\2\0\12\4\1\222\7\4\6\0\4\4"+
    "\1\223\7\0\1\4\2\0\22\4\6\0\5\4\7\0"+
    "\1\4\2\0\4\4\1\224\15\4\6\0\5\4\7\0"+
    "\1\4\2\0\11\4\1\225\10\4\6\0\5\4\7\0"+
    "\1\4\2\0\2\4\1\226\17\4\6\0\5\4\7\0"+
    "\1\4\2\0\14\4\1\227\5\4\6\0\5\4\7\0"+
    "\1\4\2\0\14\4\1\230\5\4\6\0\4\4\1\231"+
    "\7\0\1\4\2\0\22\4\6\0\5\4\7\0\1\4"+
    "\2\0\13\4\1\232\6\4\6\0\5\4\7\0\1\4"+
    "\2\0\5\4\2\233\13\4\6\0\4\4\1\116\7\0"+
    "\1\4\2\0\22\4\6\0\5\4\7\0\1\4\2\0"+
    "\5\4\2\234\13\4\6\0\5\4\7\0\1\4\2\0"+
    "\4\4\1\235\15\4\6\0\5\4\7\0\1\4\2\0"+
    "\5\4\2\236\13\4\6\0\4\4\1\237\7\0\1\4"+
    "\2\0\22\4\6\0\5\4\7\0\1\4\2\0\17\4"+
    "\1\240\2\4\6\0\5\4\7\0\1\4\2\0\11\4"+
    "\1\241\10\4\6\0\5\4\7\0\1\4\2\0\2\4"+
    "\1\242\17\4\6\0\3\4\1\243\1\4\7\0\1\4"+
    "\2\0\22\4\6\0\5\4\7\0\1\4\2\0\5\4"+
    "\2\244\13\4\6\0\5\4\7\0\1\4\2\0\12\4"+
    "\1\245\7\4\6\0\5\4\7\0\1\4\2\0\14\4"+
    "\1\246\5\4\6\0\5\4\7\0\1\4\2\0\5\4"+
    "\2\247\13\4\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5187];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\7\1\1\11\2\1\1\11\1\1\2\11"+
    "\15\1\1\11\1\0\4\1\1\11\17\1\1\0\1\1"+
    "\1\0\23\1\1\0\25\1\1\11\107\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }
    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexerCup(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LexerCup(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 27: 
          { return new Symbol(sym.PRFUN, yychar, yyline, yytext());
          }
        case 40: break;
        case 5: 
          { return new Symbol(sym.OAS, yychar, yyline, yytext());
          }
        case 41: break;
        case 13: 
          { return new Symbol(sym.PRAN, yychar, yyline, yytext());
          }
        case 42: break;
        case 34: 
          { return new Symbol(sym.PRHE, yychar, yyline, yytext());
          }
        case 43: break;
        case 14: 
          { return new Symbol(sym.PRNO, yychar, yyline, yytext());
          }
        case 44: break;
        case 39: 
          { return new Symbol(sym.PRFO, yychar, yyline, yytext());
          }
        case 45: break;
        case 28: 
          { return new Symbol(sym.FPA, yychar, yyline, yytext());
          }
        case 46: break;
        case 36: 
          { return new Symbol(sym.FFN, yychar, yyline, yytext());
          }
        case 47: break;
        case 7: 
          { return new Symbol(sym.OL, yychar, yyline, yytext());
          }
        case 48: break;
        case 33: 
          { return new Symbol(sym.PRER, yychar, yyline, yytext());
          }
        case 49: break;
        case 29: 
          { return new Symbol(sym.CPSO, yychar, yyline, yytext());
          }
        case 50: break;
        case 6: 
          { return new Symbol(sym.OR, yychar, yyline, yytext());
          }
        case 51: break;
        case 16: 
          { return new Symbol(sym.STR, yychar, yyline, yytext());
          }
        case 52: break;
        case 8: 
          { return new Symbol(sym.PYC, yychar, yyline, yytext());
          }
        case 53: break;
        case 9: 
          { return new Symbol(sym.DP, yychar, yyline, yytext());
          }
        case 54: break;
        case 17: 
          { return new Symbol(sym.NF, yychar, yyline, yytext());
          }
        case 55: break;
        case 37: 
          { return new Symbol(sym.PRDO, yychar, yyline, yytext());
          }
        case 56: break;
        case 22: 
          { return new Symbol(sym.VL, yychar, yyline, yytext());
          }
        case 57: break;
        case 23: 
          { return new Symbol(sym.FI, yychar, yyline, yytext());
          }
        case 58: break;
        case 20: 
          { return new Symbol(sym.PRLR, yychar, yyline, yytext());
          }
        case 59: break;
        case 19: 
          { return new Symbol(sym.PRPA, yychar, yyline, yytext());
          }
        case 60: break;
        case 15: 
          { return new Symbol(sym.PRSI, yychar, yyline, yytext());
          }
        case 61: break;
        case 21: 
          { return new Symbol(sym.PRSO, yychar, yyline, yytext());
          }
        case 62: break;
        case 12: 
          { return new Symbol(sym.CS, yychar, yyline, yytext());
          }
        case 63: break;
        case 30: 
          { return new Symbol(sym.FSN, yychar, yyline, yytext());
          }
        case 64: break;
        case 26: 
          { return new Symbol(sym.PRRR, yychar, yyline, yytext());
          }
        case 65: break;
        case 3: 
          { return new Symbol(sym.ID, yychar, yyline, yytext());
          }
        case 66: break;
        case 4: 
          { return new Symbol(sym.NE, yychar, yyline, yytext());
          }
        case 67: break;
        case 38: 
          { return new Symbol(sym.FMS, yychar, yyline, yytext());
          }
        case 68: break;
        case 10: 
          { return new Symbol(sym.PA, yychar, yyline, yytext());
          }
        case 69: break;
        case 35: 
          { return new Symbol(sym.PRAO, yychar, yyline, yytext());
          }
        case 70: break;
        case 11: 
          { return new Symbol(sym.PCD, yychar, yyline, yytext());
          }
        case 71: break;
        case 24: 
          { return new Symbol(sym.PRSN, yychar, yyline, yytext());
          }
        case 72: break;
        case 1: 
          { return new Symbol(sym.error, yychar, yyline, yytext());
          }
        case 73: break;
        case 2: 
          { /*Ignore*/
          }
        case 74: break;
        case 25: 
          { return new Symbol(sym.PRHR, yychar, yyline, yytext());
          }
        case 75: break;
        case 31: 
          { return new Symbol(sym.PRMS, yychar, yyline, yytext());
          }
        case 76: break;
        case 32: 
          { return new Symbol(sym.PRES, yychar, yyline, yytext());
          }
        case 77: break;
        case 18: 
          { return new Symbol(sym.PRQE, yychar, yyline, yytext());
          }
        case 78: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
