
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 16 18:38:37 CST 2019
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FITN = 33;
  public static final int PRNO = 14;
  public static final int PRFUN = 9;
  public static final int FPA = 26;
  public static final int STR = 22;
  public static final int SL = 2;
  public static final int PRHE = 28;
  public static final int VL = 21;
  public static final int PCD = 31;
  public static final int PC = 32;
  public static final int PRQE = 20;
  public static final int PA = 30;
  public static final int FFN = 27;
  public static final int CS = 4;
  public static final int PRAO = 10;
  public static final int PRAN = 6;
  public static final int CPSO = 34;
  public static final int PRDO = 18;
  public static final int PRMS = 37;
  public static final int OR = 5;
  public static final int FI = 23;
  public static final int OL = 36;
  public static final int PRSO = 29;
  public static final int PRSN = 16;
  public static final int ID = 38;
  public static final int PRSI = 13;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PRPA = 3;
  public static final int PRFO = 35;
  public static final int PRLR = 12;
  public static final int PRRR = 19;
  public static final int OAS = 41;
  public static final int NF = 39;
  public static final int NE = 40;
  public static final int FMS = 25;
  public static final int PRES = 15;
  public static final int DP = 8;
  public static final int PRER = 11;
  public static final int FSN = 24;
  public static final int PYC = 7;
  public static final int PRHR = 17;
}

